CMS/Areas/Movie/Controllers/CreateMovieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CMS.Repository;



namespace CMS.Areas.Movie.Controllers
{    
    public class CreateMovieController : Controller
    {
        private readonly IMovieRepository repository;

        public CreateMovieController(IMovieRepository objIrepository)
        {
            repository = objIrepository;
        }

        private const string viewName = "~/Views/Movie/Create.cshtml";

        public ActionResult Index()
        {
            return View(viewName);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Movie movie)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    repository.InsertOrUpdate(movie);
                    repository.Save();
                }
                catch
                {
                    //some error log
                }
                
                //return RedirectToAction("/listmovie/index");
            }

            return RedirectToAction("index","listmovie");
        }
    }
}

CMS/Areas/Movie/Controllers/DetailMovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using CMS.Repository;

namespace CMS.Areas.Movie.Controllers
{
    public class DetailMovieController : Controller
    {
        private readonly IMovieRepository repository;

        public DetailMovieController(IMovieRepository objIrepository)
        {
            repository = objIrepository;
        }

        private const string viewName = "~/Views/Movie/Detail.cshtml";

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = repository.GetById(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(viewName, movie);
        }
    }
}

CMS/Areas/Movie/Controllers/EditMovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using CMS.Repository;

namespace CMS.Areas.Movie.Controllers
{
    public class EditMovieController : Controller
    {
        private readonly IMovieRepository repository;

        public EditMovieController(IMovieRepository objIrepository)
        {
            repository = objIrepository;
        }

        private const string viewName = "~/Views/Movie/Edit.cshtml";
        // GET: Movie/EditMovie
        public ActionResult Index()
        {
            return View(viewName);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie move = repository.GetById(id);
            if (move == null)
            {
                return HttpNotFound();
            }
            return View(viewName, move);
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Movie movie)
        {
            if (ModelState.IsValid)
            {
                repository.InsertOrUpdate(movie);
                repository.Save();                
            }
            return RedirectToAction("index", "listmovie");
        }
    }
}

CMS/Areas/Movie/Controllers/ListMovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using CMS.Repository;

namespace CMS.Areas.Movie.Controllers
{
    public class ListMovieController : Controller
    {
        private readonly IMovieRepository repository;

        public ListMovieController(IMovieRepository objIrepository)
        {
            repository = objIrepository;
        }

        private const string viewName = "~/Views/Movie/List.cshtml";

        public ActionResult Index()
        {
            return View(viewName, repository.GetAll);
        }

        
        public ActionResult DeleteConfirmed(int id)
        {
            repository.Delete(id);
            repository.Save();
            return RedirectToAction("index", "listmovie");
        }
    }
}

CMS/Views/Movie/Create.cshtml
@model CMS.Areas.Movie.Movie

@{
    ViewBag.Title = "Movie";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "CreateMovie", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CMS/Views/Movie/Detail.cshtml
@model CMS.Areas.Movie.Movie

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", "EditMovie", new { id = Model.Id }, null) |
    @Html.ActionLink("Back to List", "Index", "ListMovie", null)
</p>

CMS/Views/Movie/Edit.cshtml
@model CMS.Areas.Movie.Movie

@{
    ViewBag.Title = "Movie";
}

<h2>Edit Movie</h2>

@using (Html.BeginForm("Edit", "EditMovie", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CMS/Views/Movie/List.cshtml
@model IEnumerable<CMS.Areas.Movie.Movie>

@{
    ViewBag.Title = "Index";
}

<h2>List of Movies</h2>

<p>
    <a href="/createmovie/index">Create New</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Year)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "EditMovie", new { id = item.Id }, null) |
                @Html.ActionLink("Details", "Details", "DetailMovie", new { id = item.Id }, null) |
                @Html.ActionLink("Delete", "DeleteConfirmed", "ListMovie", new { id = item.Id }, null)
            </td>
        </tr>
    }

</table>